spring:
  application:
    name: vets-service
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cache:
    cache-names: vets
  profiles:
    active: production
  cloud:
    consul:
      host: ${CONSUL_ADDR:10.9.60.43}
      port: ${CONSUL_PORT:30000}
      discovery:
        heartbeat:
          enabled: true

---
spring:
  config:
    activate:
      on-profile: k8s
    import: configserver:http://config-server:8888
