kind: Deployment
apiVersion: apps/v1
metadata:
  name: consul-deployment
  labels:
    app: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: consul:latest
          env:
            - name: TZ
              value: Asia/Shanghai
---

apiVersion: v1
kind: Service
metadata:
  name: consul
spec:
  ports:
    - name: http
      port: 8500
      targetPort: 8500
  selector:
    app: consul
  type: ClusterIP


---

apiVersion: v1
kind: Service
metadata:
  name: consul-nodeport
spec:
  ports:
    - name: http
      port: 8500
      targetPort: 8500
      nodePort: 30000
  selector:
    app: consul
  type: NodePort
